const https = require('https');

// Global in-memory match cache to avoid redundant network calls
const matchCache = new Map();

function fetchHttp(url, options = {}) {
    return new Promise((resolve, reject) => {
        const req = https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Referer': 'https://heardle-clone-delta.vercel.app/',
                ...options.headers
            }
        }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        resolve(data);
                    }
                } else {
                    reject(new Error(`HTTP ${res.statusCode}: ${data.slice(0, 100)}`));
                }
            });
        });

        req.on('error', reject);
        req.setTimeout(8000, () => {
            req.destroy();
            reject(new Error('Request timed out'));
        });
    });
}

function scoreCandidate(item, artist, title) {
    const snippet = item.snippet || {};
    const rawTitle = (snippet.title || '').toLowerCase();
    const channel = (snippet.channelTitle || '').toLowerCase();
    const desc = (snippet.description || '').toLowerCase();
    const targetTitle = (title || '').toLowerCase().trim();
    const targetArtist = (artist || '').toLowerCase().trim();

    let score = 50;

    // 1. YouTube Music Topic channel (+120) - Official album release without video intros
    if (channel.endsWith('- topic') || channel.includes('topic')) {
        score += 120;
    }
    if (desc.includes('provided to youtube by') || desc.includes('auto-generated by youtube') || desc.includes('released on:')) {
        score += 100;
    }

    // 2. Official Audio tag (+80)
    if (rawTitle.includes('official audio') || rawTitle.includes('(audio)') || rawTitle.includes('[audio]') || rawTitle.includes('audio officiel')) {
        score += 80;
    }

    // 3. Lyrics video (+40) - Almost always uses the studio master track
    if (rawTitle.includes('lyrics') || rawTitle.includes('paroles') || rawTitle.includes('lyric video')) {
        score += 40;
    }

    // 4. Exact / Close Title Matching (+40)
    if (targetTitle && (rawTitle === targetTitle || rawTitle.startsWith(targetTitle) || rawTitle.includes(targetTitle))) {
        score += 40;
    }
    if (targetArtist && (channel.includes(targetArtist) || rawTitle.includes(targetArtist))) {
        score += 20;
    }

    // 5. Heavy penalties for Music Videos / Clips with intros & dialogue (-150)
    if (rawTitle.includes('official video') || rawTitle.includes('official music video') || rawTitle.includes('clip officiel') || rawTitle.includes('music video') || rawTitle.includes('vidéo officielle')) {
        score -= 150;
    }
    if (channel.includes('vevo') && !rawTitle.includes('audio')) {
        score -= 100;
    }
    if (rawTitle.includes('short film') || rawTitle.includes('teaser') || rawTitle.includes('trailer') || rawTitle.includes('behind the scenes') || rawTitle.includes('making of')) {
        score -= 250;
    }

    // 6. Live / Concert / Acoustic / Remix / Cover heavy penalties (-200) unless part of original title
    const noiseWords = ['live', 'concert', 'en concert', 'en direct', 'acoustic', 'acoustique', 'cover', 'reprise', 'remix', 'instrumental', 'karaoke'];
    for (const word of noiseWords) {
        if (rawTitle.includes(word) && !targetTitle.includes(word)) {
            score -= 200;
        }
    }

    return score;
}

// 0-Quota Public Web Search Scraper
function searchYouTubeNoQuotaScrape(query) {
    return new Promise((resolve) => {
        const url = 'https://www.youtube.com/results?search_query=' + encodeURIComponent(query);
        const req = https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
            }
        }, (res) => {
            let html = '';
            res.on('data', chunk => html += chunk);
            res.on('end', () => {
                try {
                    const idx = html.indexOf('ytInitialData = ');
                    if (idx !== -1) {
                        const start = idx + 'ytInitialData = '.length;
                        const end = html.indexOf(';</script>', start);
                        if (end !== -1) {
                            const jsonStr = html.substring(start, end);
                            const data = JSON.parse(jsonStr);
                            const contents = data.contents?.twoColumnSearchResultsRenderer?.primaryContents?.sectionListRenderer?.contents || [];
                            const videos = [];
                            
                            for (const section of contents) {
                                const items = section.itemSectionRenderer?.contents || [];
                                for (const item of items) {
                                    const v = item.videoRenderer;
                                    if (v && v.videoId) {
                                        const title = v.title?.runs?.map(r => r.text).join('') || '';
                                        const channel = v.ownerText?.runs?.map(r => r.text).join('') || '';
                                        const desc = v.detailedMetadataSnippets?.[0]?.snippetText?.runs?.map(r => r.text).join('') || '';
                                        videos.push({
                                            videoId: v.videoId,
                                            snippet: {
                                                title: title,
                                                channelTitle: channel,
                                                description: desc
                                            }
                                        });
                                    }
                                }
                            }
                            if (videos.length > 0) return resolve(videos);
                        }
                    }

                    // Fallback regex matching
                    const videoIds = [...html.matchAll(/\/watch\?v=([a-zA-Z0-9_-]{11})/g)].map(m => m[1]);
                    const unique = [...new Set(videoIds)].slice(0, 10);
                    resolve(unique.map(id => ({ videoId: id, snippet: { title: '', channelTitle: '', description: '' } })));
                } catch (e) {
                    console.warn('Scrape parse fallback:', e.message);
                    resolve([]);
                }
            });
        });

        req.on('error', () => resolve([]));
        req.setTimeout(6000, () => {
            req.destroy();
            resolve([]);
        });
    });
}

// Fallback: Official YouTube Data API (only if scrape yields 0 results)
async function searchYouTubeViaOfficialAPI(query, apiKey) {
    try {
        const searchUrl = `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(query)}&type=video&maxResults=10&key=${encodeURIComponent(apiKey)}`;
        const data = await fetchHttp(searchUrl);
        return (data && Array.isArray(data.items)) ? data.items.map(it => ({
            videoId: it.id?.videoId,
            snippet: it.snippet || {}
        })) : [];
    } catch (e) {
        console.warn('Official YouTube API search attempt failed:', query, e.message);
        return [];
    }
}

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    const { q, query: queryParam, artist = '', title = '' } = req.query;
    const cleanArtist = artist.trim();
    const cleanTitle = title.trim();
    const rawQuery = q || queryParam || `${cleanArtist} ${cleanTitle}`.trim();

    if (!rawQuery) {
        return res.status(400).json({ error: 'Missing query parameters (q, artist, or title).' });
    }

    // Check In-Memory Cache (0 network, <1ms)
    const cacheKey = `${cleanArtist.toLowerCase()}|||${cleanTitle.toLowerCase()}|||${rawQuery.toLowerCase()}`;
    if (matchCache.has(cacheKey)) {
        const cached = matchCache.get(cacheKey);
        return res.status(200).json({
            ...cached,
            cached: true,
            source: 'cache'
        });
    }

    try {
        const baseTerms = (cleanArtist && cleanTitle) ? `${cleanArtist} ${cleanTitle}` : rawQuery.replace(/audio/gi, '').trim();

        // 1. Try 0-Quota Public Web Search Scraper (Primary)
        let candidates = await searchYouTubeNoQuotaScrape(`${baseTerms} Topic`);
        let sourceUsed = 'no_quota_scrape';

        if (candidates.length === 0) {
            candidates = await searchYouTubeNoQuotaScrape(`${baseTerms} Official Audio`);
        }
        if (candidates.length === 0) {
            candidates = await searchYouTubeNoQuotaScrape(rawQuery);
        }

        // 2. If scraping failed (e.g. rate limit/network), fallback to Official API (Backup)
        if (candidates.length === 0) {
            const apiKey = process.env.YOUTUBE_API_KEY || 'AIzaSyDA4eTxUyaC8s8rHlOp4AjKNqjycDljte4';
            candidates = await searchYouTubeViaOfficialAPI(`${baseTerms} Topic`, apiKey);
            sourceUsed = 'official_api_fallback';

            if (candidates.length === 0) {
                candidates = await searchYouTubeViaOfficialAPI(`${baseTerms} Official Audio`, apiKey);
            }
            if (candidates.length === 0) {
                candidates = await searchYouTubeViaOfficialAPI(rawQuery, apiKey);
            }
        }

        if (candidates.length === 0) {
            return res.status(404).json({ error: 'No matching YouTube video found.' });
        }

        // Rank candidates by audio fidelity score
        const scored = candidates
            .filter(item => item.videoId)
            .map(item => ({
                videoId: item.videoId,
                title: item.snippet?.title || '',
                channel: item.snippet?.channelTitle || '',
                score: scoreCandidate(item, cleanArtist, cleanTitle)
            }))
            .sort((a, b) => b.score - a.score);

        if (scored.length === 0) {
            return res.status(404).json({ error: 'No playable video candidates found.' });
        }

        const best = scored[0];
        const result = {
            success: true,
            videoId: best.videoId,
            title: best.title,
            channel: best.channel,
            score: best.score,
            source: sourceUsed
        };

        // Cache result
        matchCache.set(cacheKey, result);

        return res.status(200).json(result);

    } catch (err) {
        console.error('Match audio error:', err);
        return res.status(500).json({
            error: `Failed to search YouTube: ${err.message}`
        });
    }
};
