const https = require('https');

function fetchHttp(url, options = {}) {
    return new Promise((resolve, reject) => {
        const req = https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'Referer': 'https://heardle-clone-delta.vercel.app/',
                ...options.headers
            }
        }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        resolve(data);
                    }
                } else {
                    reject(new Error(`HTTP ${res.statusCode}: ${data.slice(0, 100)}`));
                }
            });
        });

        req.on('error', reject);
        req.setTimeout(8000, () => {
            req.destroy();
            reject(new Error('Request timed out'));
        });
    });
}

function scoreCandidate(item, artist, title) {
    const snippet = item.snippet || {};
    const rawTitle = (snippet.title || '').toLowerCase();
    const channel = (snippet.channelTitle || '').toLowerCase();
    const desc = (snippet.description || '').toLowerCase();
    const targetTitle = (title || '').toLowerCase().trim();
    const targetArtist = (artist || '').toLowerCase().trim();

    let score = 50;

    // 1. YouTube Music Topic channel (+120) - Official album release without video intros
    if (channel.endsWith('- topic') || channel.includes('topic')) {
        score += 120;
    }
    if (desc.includes('provided to youtube by') || desc.includes('auto-generated by youtube') || desc.includes('released on:')) {
        score += 100;
    }

    // 2. Official Audio tag (+60)
    if (rawTitle.includes('official audio') || rawTitle.includes('(audio)') || rawTitle.includes('[audio]') || rawTitle.includes('audio officiel')) {
        score += 60;
    }

    // 3. Lyrics video (+30) - Almost always uses the studio master track
    if (rawTitle.includes('lyrics') || rawTitle.includes('paroles') || rawTitle.includes('lyric video')) {
        score += 30;
    }

    // 4. Exact / Close Title Matching (+40)
    if (targetTitle && (rawTitle === targetTitle || rawTitle.startsWith(targetTitle))) {
        score += 40;
    }
    if (targetArtist && (channel.includes(targetArtist) || rawTitle.includes(targetArtist))) {
        score += 20;
    }

    // 5. Heavy penalties for Music Videos / Clips with intros & dialogue (-100)
    if (rawTitle.includes('official video') || rawTitle.includes('official music video') || rawTitle.includes('clip officiel') || rawTitle.includes('music video') || rawTitle.includes('vidéo officielle')) {
        score -= 100;
    }
    if (channel.includes('vevo')) {
        score -= 70;
    }
    if (rawTitle.includes('short film') || rawTitle.includes('teaser') || rawTitle.includes('trailer') || rawTitle.includes('behind the scenes') || rawTitle.includes('making of')) {
        score -= 200;
    }

    // 6. Live / Concert / Acoustic / Remix / Cover penalties unless part of original title (-80)
    const noiseWords = ['live', 'concert', 'en concert', 'en direct', 'acoustic', 'acoustique', 'cover', 'reprise', 'remix', 'instrumental', 'karaoke'];
    for (const word of noiseWords) {
        if (rawTitle.includes(word) && !targetTitle.includes(word)) {
            score -= 80;
        }
    }

    return score;
}

async function searchYouTubeCandidates(query, apiKey) {
    try {
        const searchUrl = `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(query)}&type=video&maxResults=10&key=${encodeURIComponent(apiKey)}`;
        const data = await fetchHttp(searchUrl);
        return (data && Array.isArray(data.items)) ? data.items : [];
    } catch (e) {
        console.warn('YouTube search attempt failed:', query, e.message);
        return [];
    }
}

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    const { q, query: queryParam, artist = '', title = '' } = req.query;
    const rawQuery = q || queryParam || `${artist} ${title}`.trim();

    if (!rawQuery) {
        return res.status(400).json({ error: 'Missing query parameters (q, artist, or title).' });
    }

    const apiKey = process.env.YOUTUBE_API_KEY || 'AIzaSyDA4eTxUyaC8s8rHlOp4AjKNqjycDljte4';

    try {
        // Build prioritized search queries: Topic first, then Audio
        const cleanArtist = artist.trim();
        const cleanTitle = title.trim();
        const baseTerms = (cleanArtist && cleanTitle) ? `${cleanArtist} ${cleanTitle}` : rawQuery.replace(/audio/gi, '').trim();

        let candidates = await searchYouTubeCandidates(`${baseTerms} Topic`, apiKey);

        // If no items returned or all penalized, fallback search
        if (candidates.length === 0) {
            candidates = await searchYouTubeCandidates(`${baseTerms} Official Audio`, apiKey);
        }
        if (candidates.length === 0) {
            candidates = await searchYouTubeCandidates(rawQuery, apiKey);
        }

        if (candidates.length === 0) {
            return res.status(404).json({ error: 'No matching YouTube video found.' });
        }

        // Rank candidates by audio fidelity score
        const scored = candidates
            .filter(item => item.id && item.id.videoId)
            .map(item => ({
                videoId: item.id.videoId,
                title: item.snippet?.title || '',
                channel: item.snippet?.channelTitle || '',
                score: scoreCandidate(item, cleanArtist, cleanTitle)
            }))
            .sort((a, b) => b.score - a.score);

        if (scored.length === 0) {
            return res.status(404).json({ error: 'No playable video candidates found.' });
        }

        const best = scored[0];
        return res.status(200).json({
            success: true,
            videoId: best.videoId,
            title: best.title,
            channel: best.channel,
            score: best.score
        });

    } catch (err) {
        console.error('Match audio error:', err);
        return res.status(500).json({
            error: `Failed to search YouTube: ${err.message}`
        });
    }
};
