const https = require('https');

// Global in-memory match cache to avoid redundant network calls
const matchCache = new Map();

function fetchHttp(url, options = {}) {
    return new Promise((resolve, reject) => {
        const req = https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Referer': 'https://heardle-clone-delta.vercel.app/',
                ...options.headers
            }
        }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        resolve(data);
                    }
                } else {
                    reject(new Error(`HTTP ${res.statusCode}: ${data.slice(0, 100)}`));
                }
            });
        });

        req.on('error', reject);
        req.setTimeout(8000, () => {
            req.destroy();
            reject(new Error('Request timed out'));
        });
    });
}

function normalizeStr(str) {
    return (str || '')
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^\w\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function getEssentialWords(str) {
    const stopWords = new Set(['the', 'a', 'an', 'and', 'or', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by', 'la', 'le', 'les', 'de', 'du', 'des', 'un', 'une', 'et']);
    const words = normalizeStr(str)
        .split(' ')
        .filter(w => w.length > 0 && !stopWords.has(w));
    return words.length > 0 ? words : normalizeStr(str).split(' ').filter(w => w.length > 0);
}

function scoreCandidate(item, targetArtist, targetTitle) {
    const snippet = item.snippet || {};
    const rawTitle = (snippet.title || '').toLowerCase();
    const channel = (snippet.channelTitle || '').toLowerCase();
    const desc = (snippet.description || '').toLowerCase();

    const normRawTitle = normalizeStr(rawTitle);
    const normTargetTitle = normalizeStr(targetTitle);
    const normTargetArtist = normalizeStr(targetArtist);

    const titleWords = getEssentialWords(targetTitle);
    const artistWords = getEssentialWords(targetArtist);

    let score = 0;

    // 1. MUST MATCH TARGET TITLE
    const matchedTitleWords = titleWords.filter(w => normRawTitle.includes(w));
    const titleMatchRatio = titleWords.length > 0 ? (matchedTitleWords.length / titleWords.length) : 0;

    if (titleWords.length > 0 && titleMatchRatio < 0.5) {
        // Missing majority of title words -> wrong song
        return -1000;
    }

    if (normRawTitle === normTargetTitle || normRawTitle.startsWith(normTargetTitle) || normRawTitle.includes(normTargetTitle)) {
        score += 150;
    } else {
        score += Math.round(titleMatchRatio * 100);
    }

    // 2. ARTIST MATCHING
    const matchedArtistWords = artistWords.filter(w => normRawTitle.includes(w) || channel.includes(w));
    const artistMatchRatio = artistWords.length > 0 ? (matchedArtistWords.length / artistWords.length) : 0;

    if (artistMatchRatio >= 0.5) {
        score += 80;
    } else if (artistWords.length > 0) {
        score -= 100; // Artist name nowhere in title or channel
    }

    // 3. CHANNEL & AUDIO SOURCE
    const isTopic = channel.endsWith('- topic') || channel.includes('topic');
    const isOfficialChannel = artistWords.length > 0 && channel.includes(artistWords[0]);
    const isAutoGenerated = desc.includes('provided to youtube by') || desc.includes('auto-generated by youtube') || desc.includes('released on:');

    if (isTopic && isAutoGenerated) {
        score += 100; // Perfect studio release track
    } else if (isTopic) {
        score += 60;
    }

    if (isOfficialChannel) {
        score += 40;
    }

    // Official audio tags
    if (rawTitle.includes('official audio') || rawTitle.includes('(audio)') || rawTitle.includes('[audio]') || rawTitle.includes('audio officiel')) {
        score += 70;
    } else if (rawTitle.includes('lyrics') || rawTitle.includes('paroles') || rawTitle.includes('lyric video')) {
        score += 40;
    }

    // 4. PENALTIES FOR UNWANTED VERSIONS (unless requested in target title)
    const unwantedTerms = [
        'remix', 'mix', 'live', 'concert', 'acoustic', 'acoustique', 'cover', 'reprise', 
        'karaoke', 'instrumental', 'drumless', 'slowed', 'reverb', 'sped up', 'speed up', 
        'nightcore', '8d audio', 'tribute', 'mashup', 'parody', 'reaction', 'tutorial', 
        'lesson', 'behind the scenes', 'making of', 'teaser', 'trailer', 'short film',
        'bass boost', 'orchestral', 'extended', 'edit', 'vip', 'demo', 'session'
    ];

    for (const term of unwantedTerms) {
        if (normRawTitle.includes(term) && !normTargetTitle.includes(term)) {
            score -= 250;
        }
    }

    // Video intro penalty for music videos (dialogue / silence before music)
    if (rawTitle.includes('official video') || rawTitle.includes('official music video') || rawTitle.includes('clip officiel') || rawTitle.includes('vidéo officielle')) {
        score -= 60;
    }

    return score;
}

// Search Deezer for direct 30s preview MP3 URL
async function fetchDeezerPreview(artist, title) {
    try {
        const cleanA = (artist || '').split(',')[0].trim();
        const cleanT = (title || '').trim();
        const query = `${cleanA} ${cleanT}`.trim();
        if (!query) return null;

        const searchUrl = `https://api.deezer.com/search?q=${encodeURIComponent(query)}&limit=5`;
        const data = await fetchHttp(searchUrl);
        if (data && Array.isArray(data.data) && data.data.length > 0) {
            const normTitle = normalizeStr(cleanT);
            for (const item of data.data) {
                if (item.preview) {
                    const normItemTitle = normalizeStr(item.title_short || item.title || '');
                    if (normItemTitle.includes(normTitle) || normTitle.includes(normItemTitle)) {
                        return item.preview;
                    }
                }
            }
            if (data.data[0].preview) {
                return data.data[0].preview;
            }
        }
    } catch (e) {
        // silent fallback
    }
    return null;
}

// 0-Quota Public Web Search Scraper
function searchYouTubeNoQuotaScrape(query) {
    return new Promise((resolve) => {
        const url = 'https://www.youtube.com/results?search_query=' + encodeURIComponent(query);
        const req = https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
            }
        }, (res) => {
            let html = '';
            res.on('data', chunk => html += chunk);
            res.on('end', () => {
                try {
                    const idx = html.indexOf('ytInitialData = ');
                    if (idx !== -1) {
                        const start = idx + 'ytInitialData = '.length;
                        const end = html.indexOf(';</script>', start);
                        if (end !== -1) {
                            const jsonStr = html.substring(start, end);
                            const data = JSON.parse(jsonStr);
                            const contents = data.contents?.twoColumnSearchResultsRenderer?.primaryContents?.sectionListRenderer?.contents || [];
                            const videos = [];
                            
                            for (const section of contents) {
                                const items = section.itemSectionRenderer?.contents || [];
                                for (const item of items) {
                                    const v = item.videoRenderer;
                                    if (v && v.videoId) {
                                        const title = v.title?.runs?.map(r => r.text).join('') || '';
                                        const channel = v.ownerText?.runs?.map(r => r.text).join('') || '';
                                        const desc = v.detailedMetadataSnippets?.[0]?.snippetText?.runs?.map(r => r.text).join('') || '';
                                        videos.push({
                                            videoId: v.videoId,
                                            snippet: {
                                                title: title,
                                                channelTitle: channel,
                                                description: desc
                                            }
                                        });
                                    }
                                }
                            }
                            if (videos.length > 0) return resolve(videos);
                        }
                    }

                    // Fallback regex matching
                    const videoIds = [...html.matchAll(/\/watch\?v=([a-zA-Z0-9_-]{11})/g)].map(m => m[1]);
                    const unique = [...new Set(videoIds)].slice(0, 10);
                    resolve(unique.map(id => ({ videoId: id, snippet: { title: '', channelTitle: '', description: '' } })));
                } catch (e) {
                    console.warn('Scrape parse fallback:', e.message);
                    resolve([]);
                }
            });
        });

        req.on('error', () => resolve([]));
        req.setTimeout(6000, () => {
            req.destroy();
            resolve([]);
        });
    });
}

// Fallback: Official YouTube Data API (only if scrape yields 0 results)
async function searchYouTubeViaOfficialAPI(query, apiKey) {
    try {
        const searchUrl = `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(query)}&type=video&maxResults=10&key=${encodeURIComponent(apiKey)}`;
        const data = await fetchHttp(searchUrl);
        return (data && Array.isArray(data.items)) ? data.items.map(it => ({
            videoId: it.id?.videoId,
            snippet: it.snippet || {}
        })) : [];
    } catch (e) {
        console.warn('Official YouTube API search attempt failed:', query, e.message);
        return [];
    }
}

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    const { q, query: queryParam, artist = '', title = '' } = req.query;
    const cleanArtist = artist.trim();
    const cleanTitle = title.trim();
    const rawQuery = q || queryParam || `${cleanArtist} ${cleanTitle}`.trim();

    if (!rawQuery) {
        return res.status(400).json({ error: 'Missing query parameters (q, artist, or title).' });
    }

    // Check In-Memory Cache (0 network, <1ms)
    const cacheKey = `${cleanArtist.toLowerCase()}|||${cleanTitle.toLowerCase()}|||${rawQuery.toLowerCase()}`;
    if (matchCache.has(cacheKey)) {
        const cached = matchCache.get(cacheKey);
        return res.status(200).json({
            ...cached,
            cached: true,
            source: 'cache'
        });
    }

    try {
        const baseTerms = (cleanArtist && cleanTitle) ? `${cleanArtist} ${cleanTitle}` : rawQuery.replace(/audio/gi, '').trim();

        // 1. Fetch direct Deezer preview in parallel
        const deezerPreviewPromise = fetchDeezerPreview(cleanArtist, cleanTitle);

        // 2. Try 0-Quota Public Web Search Scraper (Primary)
        let candidates = await searchYouTubeNoQuotaScrape(`${baseTerms} Official Audio`);
        let sourceUsed = 'no_quota_scrape';

        if (candidates.length === 0) {
            candidates = await searchYouTubeNoQuotaScrape(`${baseTerms} Topic`);
        }
        if (candidates.length === 0) {
            candidates = await searchYouTubeNoQuotaScrape(rawQuery);
        }

        // 3. Fallback to Official API if needed
        if (candidates.length === 0) {
            const apiKey = process.env.YOUTUBE_API_KEY || 'AIzaSyDA4eTxUyaC8s8rHlOp4AjKNqjycDljte4';
            candidates = await searchYouTubeViaOfficialAPI(`${baseTerms} Official Audio`, apiKey);
            sourceUsed = 'official_api_fallback';

            if (candidates.length === 0) {
                candidates = await searchYouTubeViaOfficialAPI(`${baseTerms} Topic`, apiKey);
            }
            if (candidates.length === 0) {
                candidates = await searchYouTubeViaOfficialAPI(rawQuery, apiKey);
            }
        }

        const audioPreviewUrl = await deezerPreviewPromise;

        // Rank candidates by audio fidelity score
        const scored = candidates
            .filter(item => item.videoId)
            .map(item => ({
                videoId: item.videoId,
                title: item.snippet?.title || '',
                channel: item.snippet?.channelTitle || '',
                score: scoreCandidate(item, cleanArtist, cleanTitle)
            }))
            .filter(item => item.score > -500) // Exclude completely mismatched songs
            .sort((a, b) => b.score - a.score);

        if (scored.length === 0 && !audioPreviewUrl) {
            return res.status(404).json({ error: 'No matching video or audio preview found.' });
        }

        const best = scored.length > 0 ? scored[0] : null;
        const result = {
            success: true,
            videoId: best ? best.videoId : null,
            audioPreviewUrl: audioPreviewUrl || null,
            title: best ? best.title : cleanTitle,
            channel: best ? best.channel : cleanArtist,
            score: best ? best.score : 0,
            source: sourceUsed
        };

        // Cache result
        matchCache.set(cacheKey, result);

        return res.status(200).json(result);

    } catch (err) {
        console.error('Match audio error:', err);
        return res.status(500).json({
            error: `Failed to search audio match: ${err.message}`
        });
    }
};
